### ISSUE TITLE
Add Previous Move Highlight

### ISSUE THREAD

**Issue by haylau** [haydenlauritzen/DuckFish#4]
Add WPF Databinding to tile background colors so they can be changed

**Comment by gotti619** [comment]
Hi,
I've seen your project and I've added a previous move highlight. I've never worked on a GitHub project together, but I'll probably commit the changes later :)

Nice project :)

![image](https://user-images.githubusercontent.com/18140323/181232239-a82c71c9-8773-4c04-9d15-55231a37b3f9.png)

**Comment by haylau** [comment]
Awesome! I work on this project in my spare time and will happily look at anything you send over. On another note, I was curious how you found the project, especially considering how many of them are on githhub.

**Comment by gotti619** [comment]
> Awesome! I work on this project in my spare time and will happily look at anything you send over. On another note, I was curious how you found the project, especially considering how many of them are on githhub.

I've done the changes, but they're not perfect ;) Hope you can see the changes.
I've simply searched for "C# wpf" and your project was the first one. Since I'm playing chess myself (once in a while), I liked your project, downloaded it and thought I could do some changes, too :)

**Comment by haylau** [comment]
Make sure you push your local commits to your forked repo if you want me to see them

You can also open a pull request if you'd like. 

Thanks!

**Comment by gotti619** [comment]
I did a pull request, but I think I somehow fucked up :D

Just use the code you actually need, so `<UniformGrid Name="board" Grid.Column="2" Grid.Row="2" Columns="8" Rows="8">` in your MainWindow.xaml and also this:


```
private void UpdateMove(DragEventArgs from, object to)
        {
            ClearBoardColors();
            UpdateImage(to);

            if (from.Data.GetData(DataFormats.Serializable) is not Image fromImg) return;
            string? fromTile = fromImg.Tag.ToString();
            if (fromTile == null) return;
            UpdateImage(fromImg);
            (fromImg.Parent as UniformGrid).Background = new SolidColorBrush(Colors.LightCoral);
        }
        
        private void ClearBoardColors()
        {
            int rows = board.Rows;
            int columns = board.Columns;

            foreach (var children in board.Children)
            {
                if (children is UniformGrid grid)
                {
                    int index = board.Children.IndexOf(grid);

                    int row = index / columns;  // divide
                    int column = index % columns;  // modulus

                    if (row % 2 == 0)
                    {
                        if (column % 2 == 0)
                        {
                            var lightTile = App.Current.Resources["LightTile"].ToString();
                            grid.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString(lightTile));
                        }
                        else
                        {
                            var darkTile = App.Current.Resources["DarkTile"].ToString();
                            grid.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString(darkTile));
                        }
                    }
                    else
                    {
                        if (column % 2 != 0)
                        {
                            var lightTile = App.Current.Resources["LightTile"].ToString();
                            grid.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString(lightTile));
                        }
                        else
                        {
                            var darkTile = App.Current.Resources["DarkTile"].ToString();
                            grid.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString(darkTile));
                        }
                    }
                }
            }
        }
```

I'll do a new fork after your commit. 
Should I fork main or dev?

**Comment by haylau** [comment]
Merged successfully with some minor refactoring :)
